---
title: 'Reproducible Research: Course Project 2'
author: "John Goodwin"
date: "May 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2", "StormData.csv.bz2")

storm <- read_csv("StormData.csv.bz2")

```




```{r}
storm <- storm %>% mutate(PROPDMG_factor = recode(PROPDMGEXP,
                                         K = 1000,
                                         M = 1000000,
                                         B = 1000000000,
                                         .missing = 0,
                                         .default = 0),
                 CROPDMG_factor = recode(CROPDMGEXP,
                                         K = 1000,
                                         M = 1000000,
                                         B = 1000000000,
                                         .missing = 0,
                                         .default = 0),
                 PROPDMG = PROPDMG * PROPDMG_factor,
                 CROPDMG = CROPDMG * CROPDMG_factor)

```

```{r}
library(tidytext)

storm %>% group_by(EVTYPE) %>% summarise(PROPDMG = mean(PROPDMG),
                                         cnt = n()) %>% View

event_text <- storm %>% select(EVTYPE) %>% mutate(line = 1:n()) %>% 
  unnest_tokens(word, EVTYPE)%>%
  count(word, sort = TRUE)

data("stop_words")

desc_text <- storm %>% select(REMARKS) %>%
  mutate(line = 1:n()) %>% 
  unnest_tokens(word, REMARKS) %>%
  count(word, sort = TRUE) %>%
  anti_join(stop_words) %>% 
  filter(!word %in% c("narrative", "county"), !is.na(word))

event_desc <- storm %>% filter(!is.na(REMARKS)) %>%
  select(REFNUM, REMARKS) %>%
  unnest_tokens(word, REMARKS) %>%
  anti_join(stop_words) %>% 
  filter(!word %in% c("narrative", "county"), !is.na(word)) %>%
  group_by(REFNUM) %>%
  summarise(cnt = n())

quantile(event_desc$cnt)
  

event_desc <- storm %>% filter(!is.na(REMARKS)) %>%
  select(REFNUM, REMARKS) %>%
  unnest_tokens(word, REMARKS) %>%
  anti_join(stop_words) %>% 
  filter(!word %in% c("narrative", "county"), !is.na(word)) %>%
  count(REFNUM, word)

event_desc_dtm <- event_desc %>% filter(!grepl("[0-9]",word)) %>% cast_dtm(REFNUM,word,n)

library(topicmodels)

event_desc_lda <- LDA(event_desc_dtm, k = 2, control = list(seed = 451))
```



